#include <iostream>
#include <fstream>
#include <linearc.h>

using namespace std;


int main(){

    cout << "Particle through fluid simulation.\n";
    cout << "This simulates the energy wave generated by a particle that passes through a fluid" << endl; 
    
    const int N = 5;

    double x[N][N] = {
        {1,-2,0,0,0},
        {1,-1,3,0,0},
        {0,5,2,1,0},
        {0,0,-2,1,4},
        {0,0,0,1,3}};
    
    double *X[N];
    for (int i=0; i<=N; i++) {
        X[i] = x[i];
    }

    Matrix M(X,N,N);

    M.print();
    cout << endl;
    lu_dcmp(M).print();

    return 0;
}