#include <iostream>
#include <iomanip>
#include <fstream>
#include <ctime>

#include <linearc.h>
#include <fluid.h>
#include <simulation.h>

using namespace std;

double Zero(double r, double z){
    return 0;
}

int main(){

    cout << "Particle through fluid simulation.\n";
    cout << "This simulates the energy wave generated by a particle that passes through a fluid" << endl; 
    
    Fluid fluid("LXE.txt");

    cout << "Started creating simulation object ... ";
    clock_t c_start = clock();
    
    Simulation sim(0.1,0.1,(int)100,(int)100,&fluid,&Zero);
    
    clock_t c_end = clock();
    cout << "Completed after: " << setprecision(2) << fixed << 1000. * (c_end-c_start) / CLOCKS_PER_SEC << " ms.\n" << endl;

    sim.run((int)10);


    return 0;
}