#include <iostream>
#include <fstream>

#include <linearc.h>
#include <fluid.h>
#include <simulation.h>

using namespace std;

double Zero(double r, double z){
    return 0;
}

int main(){

    cout << "Particle through fluid simulation.\n";
    cout << "This simulates the energy wave generated by a particle that passes through a fluid" << endl; 
    
    Fluid fluid("LXE.txt");

    Simulation sim(0.1,0.1,(int)10000,(int)10,&fluid,&Zero);

    sim.run((int)10);


    return 0;
}